### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Djaler** [fenrir1121/fenrir1121.github.io-old-#1]
Может, стоит сменить ссылку телеграма, а то она на мой профиль ведет)

**Comment by fenrir1121** [comment]
Спасибо! Мне почему-то казалось что я её сменил!) --С уважением, Меркурьев Виктор    23.06.2016, 01:14, "Kirill Romanov" <notifications@github.com>:Может, стоит сменить ссылку телеграма, а то она на мой профиль ведет)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
